### ISSUE TITLE
Mismatch in GenerateNextKeystreamValue4

### ISSUE THREAD

**Issue by lyumeilin01** [sanaagarwal/Comp250_A2_Tester#5]
### in the if statement, should the value be 16 or 2?
`if (value != **16**) {
            throw new AssertionError("The method generateNextKeystreamValue() is not returning the correct value. Expected value is **2** but got " + value);
        } else if (deck.head.getValue() != 16) {
            throw new AssertionError("Incorrect head after generateNextKeystreamValue()");
        }`

**Comment by sanaagarwal** [comment]
Yes sorry it should be 16. Updated now! Thanks for pointing it out!
